import type { LucideIcon } from 'lucide-react'
import {
  Code,
  FileEdit,
  FileImage,
  FileText,
  Hash,
  Image,
  LayoutGrid,
  ListOrdered,
  Palette,
  QrCode,
  RotateCcw,
  Share2,
  Split,
  Stamp,
  Merge,
} from 'lucide-react'

export type ToolStatus = 'ready' | 'new'
export type ToolCategoryId = 'image' | 'pdf' | 'text' | 'developer' | 'design' | 'utilities'

export interface ToolCatalogItem {
  id: string
  name: string
  description: string
  href: string
  status: ToolStatus
  category: ToolCategoryId
  categoryLabel: string
  icon: LucideIcon
  featured: boolean
  speedLabel: 'Instant' | 'Fast' | 'Workflow'
  highlights: string[]
}

export const toolCatalog: ToolCatalogItem[] = [
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Reduce image file size while maintaining quality for faster uploads and pages.',
    href: '/tools/image-compressor',
    status: 'ready',
    category: 'image',
    categoryLabel: 'Image Tools',
    icon: Image,
    featured: true,
    speedLabel: 'Instant',
    highlights: ['Local processing', 'Fast exports', 'Privacy-first'],
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert between common image formats with quick quality controls.',
    href: '/tools/image-converter',
    status: 'ready',
    category: 'image',
    categoryLabel: 'Image Tools',
    icon: FileImage,
    featured: false,
    speedLabel: 'Fast',
    highlights: ['JPG, PNG, WebP', 'Batch-friendly workflow', 'Quick preview'],
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images with presets and precision dimensions for web, social, and print.',
    href: '/tools/image-resizer',
    status: 'ready',
    category: 'image',
    categoryLabel: 'Image Tools',
    icon: RotateCcw,
    featured: false,
    speedLabel: 'Fast',
    highlights: ['Preset sizes', 'Pixel-accurate', 'Quick download'],
  },
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Reduce PDF file size while keeping documents readable and portable.',
    href: '/tools/pdf-compressor',
    status: 'ready',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    icon: FileText,
    featured: true,
    speedLabel: 'Workflow',
    highlights: ['Client-side', 'Simple workflow', 'Smaller files'],
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Combine multiple PDF files, reorder them, and merge only the pages you need.',
    href: '/tools/pdf-merger',
    status: 'ready',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    icon: Merge,
    featured: true,
    speedLabel: 'Workflow',
    highlights: ['Drag reorder', 'Page selection', 'Single export'],
  },
  {
    id: 'pdf-splitter',
    name: 'PDF Splitter',
    description: 'Split PDF files by page counts, selected ranges, or approximate output size.',
    href: '/tools/pdf-splitter',
    status: 'ready',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    icon: Split,
    featured: true,
    speedLabel: 'Workflow',
    highlights: ['Range-based splits', 'Multiple outputs', 'Browser-only'],
  },
  {
    id: 'pdf-rotator',
    name: 'PDF Rotator',
    description: 'Rotate all pages or selected page ranges in a PDF with one quick export.',
    href: '/tools/pdf-rotator',
    status: 'new',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    icon: RotateCcw,
    featured: true,
    speedLabel: 'Fast',
    highlights: ['90° / 180° / 270°', 'Page ranges', 'iLovePDF-style flow'],
  },
  {
    id: 'pdf-page-extractor',
    name: 'PDF Page Extractor',
    description: 'Pull only the pages you need into a clean PDF for faster sharing or review.',
    href: '/tools/pdf-page-extractor',
    status: 'new',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    icon: Split,
    featured: true,
    speedLabel: 'Fast',
    highlights: ['Custom page ranges', 'Clean export', 'Quick trimming'],
  },
  {
    id: 'pdf-organizer',
    name: 'PDF Organizer',
    description: 'Reorder, rotate, delete, and combine PDF pages in one page-first workflow.',
    href: '/tools/pdf-organizer',
    status: 'new',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    icon: LayoutGrid,
    featured: true,
    speedLabel: 'Workflow',
    highlights: ['Page sorting', 'Blank pages', 'iLovePDF-style flow'],
  },
  {
    id: 'pdf-page-numberer',
    name: 'PDF Page Numberer',
    description: 'Add page numbers to a full PDF or selected ranges with position controls.',
    href: '/tools/pdf-page-numberer',
    status: 'new',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    icon: ListOrdered,
    featured: true,
    speedLabel: 'Workflow',
    highlights: ['Top or bottom', 'Custom start number', 'Range support'],
  },
  {
    id: 'pdf-watermark',
    name: 'PDF Watermark',
    description: 'Place text or image watermarks across a PDF with control over layout and opacity.',
    href: '/tools/pdf-watermark',
    status: 'new',
    category: 'pdf',
    categoryLabel: 'PDF Tools',
    icon: Stamp,
    featured: true,
    speedLabel: 'Workflow',
    highlights: ['Text or image', 'Opacity control', 'iLovePDF-style flow'],
  },
  {
    id: 'text-summarizer',
    name: 'Text Summarizer',
    description: 'Turn long text into short, useful summaries with keyword extraction.',
    href: '/tools/text-summarizer',
    status: 'new',
    category: 'text',
    categoryLabel: 'Text Tools',
    icon: FileText,
    featured: true,
    speedLabel: 'Instant',
    highlights: ['Short or detailed', 'Bullet or paragraph', 'Keyword insights'],
  },
  {
    id: 'content-improver',
    name: 'Content Improver',
    description: 'Polish copy with grammar, tone, and clarity improvements.',
    href: '/tools/content-improver',
    status: 'ready',
    category: 'text',
    categoryLabel: 'Text Tools',
    icon: FileEdit,
    featured: false,
    speedLabel: 'Workflow',
    highlights: ['Tone controls', 'Clarity pass', 'Writing analytics'],
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate shareable QR codes with styling options and instant downloads.',
    href: '/tools/qr-generator',
    status: 'ready',
    category: 'utilities',
    categoryLabel: 'Utilities',
    icon: QrCode,
    featured: false,
    speedLabel: 'Instant',
    highlights: ['Share links', 'Styled output', 'Fast generation'],
  },
  {
    id: 'file-share',
    name: 'File Share',
    description: 'Share files with secure temporary links that expire automatically.',
    href: '/tools/file-share',
    status: 'ready',
    category: 'utilities',
    categoryLabel: 'Utilities',
    icon: Share2,
    featured: false,
    speedLabel: 'Workflow',
    highlights: ['Temporary links', 'Built-in cleanup', 'Simple sharing'],
  },
  {
    id: 'code-debugger',
    name: 'Code Debugger',
    description: 'Run a fast static pass for common code smells, syntax risks, and cleanup ideas.',
    href: '/tools/code-debugger',
    status: 'new',
    category: 'developer',
    categoryLabel: 'Developer Tools',
    icon: Code,
    featured: true,
    speedLabel: 'Instant',
    highlights: ['Risk scoring', 'Pattern checks', 'Quick fixes'],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate hashes or encrypt text with several common algorithms.',
    href: '/tools/hash-generator',
    status: 'ready',
    category: 'developer',
    categoryLabel: 'Developer Tools',
    icon: Hash,
    featured: false,
    speedLabel: 'Instant',
    highlights: ['SHA family', 'HMAC', 'AES-256'],
  },
  {
    id: 'color-palette',
    name: 'Color Palette',
    description: 'Build balanced color combinations and export them for design work.',
    href: '/tools/color-palette',
    status: 'ready',
    category: 'design',
    categoryLabel: 'Design Tools',
    icon: Palette,
    featured: false,
    speedLabel: 'Fast',
    highlights: ['Palette generation', 'Exports', 'Visual balance'],
  },
]

export const categoryOrder: ToolCategoryId[] = ['pdf', 'image', 'text', 'developer', 'design', 'utilities']

export const featuredTools = toolCatalog.filter(tool => tool.featured)

export const toolsByCategory = categoryOrder.map(category => ({
  id: category,
  label: toolCatalog.find(tool => tool.category === category)?.categoryLabel ?? category,
  tools: toolCatalog.filter(tool => tool.category === category),
}))
